name: Build

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - uses: actions/checkout@v3
      - id: setup
        uses: shogo82148/actions-setup-redis@v1
            # connect to the redis-server via TCP
      - run: redis-cli ping

      - name: Build with Maven
        run: mvn -B package -file pom.xml
